// ui/src/core/plugins/switch-to-scoped/SwitchToScoped.tsx
import type { ModalComponentProps } from '@/core/ui/modal'
import type { SwitchToScopedModalData } from '@/core/ui/modal-data'
import type { IoNamespace } from '@/core/ws'
import type { Terminal } from '@xterm/xterm'

import { useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router'

import { api } from '@/core/api'
import { escapeHtml } from '@/core/helpers/html.helper'
import { cls } from '@/core/plugins/class-names'
import { RE_ANSI } from '@/core/regex.constants'
import { settingsActions, useSettingsStore } from '@/core/settings'
import { SafeHtml } from '@/core/ui/SafeHtml'
import { toast } from '@/core/ui/toast'
import { fileSaver } from '@/core/utilities/file-saver'
import { hideXtermInputFromScreenReader, xtermFactory } from '@/core/utilities/terminal'
import { ws } from '@/core/ws'

import './switch-to-scoped.scss'

export type SwitchToScopedProps = SwitchToScopedModalData & ModalComponentProps

/** The icon-only wiki link, named for screen readers by `label` */
function moreInfoLink(label: string): string {
  return `<a href="https://github.com/homebridge/plugins/wiki/Scoped-Plugins" target="_blank" aria-label="${escapeHtml(label)}"><i class="fas fa-up-right-from-square primary-text" aria-hidden="true"></i></a>`
}
const prefix = '<span class="font-monospace">@homebridge-plugins/</span>'

/** Move a plugin to its `@homebridge-plugins/` name: install the new, remove the old, restart. */
export function SwitchToScoped({ activeModal, plugin }: SwitchToScopedProps) {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const onlineUpdateOk = useSettingsStore(state => state.env.platform !== 'win32')
  const isLightTerminalTheme = useSettingsStore(() => settingsActions.getEffectiveTerminalLightingMode() === 'light')

  const [installing, setInstalling] = useState(false)
  const [installed, setInstalled] = useState(false)
  const [uninstalling, setUninstalling] = useState(false)
  const [uninstalled, setUninstalled] = useState(false)
  const [restarting, setRestarting] = useState(false)
  const [failure, setFailure] = useState('')

  const outputRef = useRef<HTMLDivElement>(null)
  const ioRef = useRef<IoNamespace | null>(null)
  const termRef = useRef<Terminal | null>(null)
  const errorLogRef = useRef('')

  useEffect(() => {
    const term = xtermFactory.createTerminal(settingsActions.getTerminalOptions({ disableStdin: true }))
    const fitAddon = xtermFactory.createFitAddon()
    term.loadAddon(fitAddon)
    term.loadAddon(xtermFactory.createWebLinksAddon())
    termRef.current = term

    const io = ws.connectToNamespace('plugins')
    ioRef.current = io
    const target = outputRef.current!
    term.open(target)
    const xtermA11yDisposer = hideXtermInputFromScreenReader(target)
    // Defer fit() to the next tick. The modal's host element can have
    // zero size on the first tick after open, so calling fit() inline
    // would size the terminal to 0×0 and the user sees a blank pane
    // until the next resize event.
    const fitTimer = setTimeout(() => fitAddon.fit(), 0)

    const stdoutHandler = (data: string | Uint8Array) => {
      term.write(data)
      const dataCleaned = data
        .toString()
        .replace(RE_ANSI, '')
        .trimEnd()
      if (dataCleaned) {
        errorLogRef.current += `${dataCleaned}\r\n`
      }
    }
    io.socket.on('stdout', stdoutHandler)

    return () => {
      clearTimeout(fitTimer)
      // The plugins namespace is cached and shared, and `end()` keeps its
      // listeners, so detach ours before ending the session
      io.socket.off('stdout', stdoutHandler)
      io.end?.()
      xtermA11yDisposer?.()
      term.dispose()
    }
  }, [])

  const doSwitch = async () => {
    const io = ioRef.current
    const term = termRef.current
    if (!plugin || !io || !term) {
      return
    }

    // Which step is running, for the error path (state reads here would be stale)
    let step: 'install' | 'uninstall' | 'restart' = 'install'
    try {
      setInstalling(true)

      // 1. Install new plugin
      await io.request('install', {
        name: plugin.newHbScope.to,
        version: plugin.newHbScope.switch,
        termCols: term.cols,
        termRows: term.rows,
      })

      setInstalling(false)
      setInstalled(true)
      setUninstalling(true)
      step = 'uninstall'

      // 2. Uninstall old plugin
      await io.request('uninstall', {
        name: plugin.newHbScope.from,
        termCols: term.cols,
        termRows: term.rows,
      })

      setUninstalling(false)
      setUninstalled(true)
      setRestarting(true)
      step = 'restart'

      // 3. Set full service restart flag
      await api.put('/platform-tools/hb-service/set-full-service-restart-flag', {})

      activeModal.close()
      void navigate('/restart')
    } catch (error) {
      if (step === 'install') {
        setInstalling(false)
      } else if (step === 'uninstall') {
        setUninstalling(false)
      } else {
        setRestarting(false)
      }

      const message = error instanceof Error ? error.message : t('toast.api_error_generic')
      setFailure(message)
      console.error(error)
      toast.error(message, t('toast.title_error'))
    }
  }

  const downloadLogFile = () => {
    if (!plugin) {
      return
    }
    const blob = new Blob([errorLogRef.current], { type: 'text/plain;charset=utf-8' })
    fileSaver.saveAs(blob, `${plugin.name}-error.log`)
  }

  const dismissModal = () => activeModal.dismiss('Dismiss')
  const busy = installing || uninstalling || restarting

  return (
    <div className="modal-content hb-switch-to-scoped">
      <div className="modal-header">
        <h5 className="modal-title">{t('plugins.manage.scoped.switch')}</h5>
        <button
          type="button"
          className="btn-close"
          data-bs-dismiss="modal"
          aria-label={t('form.button_close')}
          disabled={busy}
          onClick={dismissModal}
        >
        </button>
      </div>
      <div className="modal-body">
        <div className="mb-3 text-center">
          <i className="fas fa-arrow-right-arrow-left primary-text icon-xl"></i>
        </div>
        <ul className="mb-0">
          <SafeHtml as="li" html={t('plugins.manage.scoped.info_1', { prefix })} />
          <li>{t('plugins.manage.scoped_message')}</li>
          <SafeHtml as="li" html={t('plugins.manage.scoped.info_2', { link: moreInfoLink(t('plugins.manage.link_scoped_wiki')) })} />
          {onlineUpdateOk
            ? <li>{t('plugins.manage.scoped.process')}</li>
            : (
                <>
                  <SafeHtml as="li" html={t('plugins.manage.scoped.windows')} />
                  <li>{t('plugins.manage.manual_update_command')}</li>
                </>
              )}
        </ul>
        {plugin && !onlineUpdateOk && (
          <pre className="mt-3 mb-0">
            {`hb-service stop
npm install -g ${plugin.newHbScope.to}@${plugin.newHbScope.switch}
npm uninstall -g ${plugin.newHbScope.from}
hb-service start`}
          </pre>
        )}
        {plugin && onlineUpdateOk && (
          <div className="text-center">
            <ul className="d-inline-block text-start mt-3 mb-3 switch-steps-list">
              <li>
                <i
                  className={cls(
                    'fa',
                    !installing && !installed && !failure && 'fa-circle-o',
                    installing && 'fa-circle-notch fa-spin',
                    installed && !failure && 'fa-check-circle green-text',
                    !installed && failure && 'fa-times-circle red-text',
                  )}
                >
                </i>
                {' '}
                {t('plugins.manage.install')}
                {' '}
                <span className="font-monospace">{plugin.newHbScope.to}</span>
              </li>
              <li>
                <i
                  className={cls(
                    'fa',
                    !uninstalling && !uninstalled && !failure && 'fa-circle-o',
                    uninstalling && 'fa-circle-notch fa-spin',
                    uninstalled && !failure && 'fa-check-circle green-text',
                    !uninstalled && failure && 'fa-times-circle red-text',
                  )}
                >
                </i>
                {' '}
                {t('plugins.manage.uninstall')}
                {' '}
                <span className="font-monospace">{plugin.newHbScope.from}</span>
              </li>
              <li>
                <i
                  className={cls(
                    'fa',
                    !restarting && !failure && 'fa-circle-o',
                    restarting && 'fa-circle-notch fa-spin',
                    failure && 'fa-times-circle red-text',
                  )}
                >
                </i>
                {' '}
                {t('menu.hbrestart.title')}
              </li>
            </ul>
          </div>
        )}
        {failure && (
          <div className="alert alert-error mb-0">
            <p>{t('plugins.manage.scoped.error')}</p>
            <p className="font-monospace">{failure}</p>
            <button type="button" className="btn btn-primary mb-0" onClick={downloadLogFile}>
              {t('form.button_download')}
            </button>
          </div>
        )}
        <div
          ref={outputRef}
          className={cls('mb-0', !isLightTerminalTheme && 'terminal-dark-bg', isLightTerminalTheme && 'terminal-light-bg')}
          id="plugin-output"
          hidden={!onlineUpdateOk || Boolean(failure)}
        >
        </div>
      </div>
      <div className="modal-footer justify-content-between">
        <div className="text-start">
          {onlineUpdateOk && (
            <button
              type="button"
              className="btn btn-elegant"
              data-bs-dismiss="modal"
              aria-label={t('form.button_close')}
              disabled={busy}
              onClick={dismissModal}
            >
              {t('form.button_close')}
            </button>
          )}
        </div>
        <div className="text-center">
          {!onlineUpdateOk && (
            <button
              type="button"
              className="btn btn-elegant"
              data-bs-dismiss="modal"
              aria-label={t('form.button_close')}
              disabled={busy}
              onClick={dismissModal}
            >
              {t('form.button_close')}
            </button>
          )}
        </div>
        <div className="text-end">
          {onlineUpdateOk && (
            <button
              type="button"
              className="btn btn-primary"
              data-bs-dismiss="modal"
              disabled={busy || !onlineUpdateOk || Boolean(failure)}
              onClick={() => void doSwitch()}
            >
              {!busy && <span>{t('form.button_continue')}</span>}
              {busy && !failure && <i className="fas fa-circle-notch fa-spin"></i>}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// ui/src/app/core/plugins/switch-to-scoped/switch-to-scoped.component.ts
import type { Terminal } from '@xterm/xterm'

import { ChangeDetectionStrategy, Component, inject, OnDestroy, OnInit, signal } from '@angular/core'
import { Router } from '@angular/router'
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap/modal'
import { TranslatePipe, TranslateService } from '@ngx-translate/core'
import { ToastrService } from 'ngx-toastr'
import { firstValueFrom } from 'rxjs'

import { ApiService } from '@/app/core/communication/api.service'
import { IoNamespace, WsService } from '@/app/core/communication/ws.service'
import { SWITCH_TO_SCOPED_MODAL_DATA } from '@/app/core/modal-data-tokens'
import { RE_ANSI } from '@/app/core/regex.constants'
import { SettingsService } from '@/app/core/ui/settings.service'
import { SAVE_AS } from '@/app/core/utilities/file-saver.factory'
import { hideXtermInputFromScreenReader } from '@/app/core/utilities/log.service'
import { TERMINAL_FACTORY } from '@/app/core/utilities/terminal.factory'

@Component({
  selector: 'app-switch-to-scoped',
  imports: [
    TranslatePipe,
  ],
  standalone: true,
  templateUrl: './switch-to-scoped.component.html',
  styleUrl: './switch-to-scoped.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchToScopedComponent implements OnInit, OnDestroy {
  // Injected dependencies
  private $saveAs = inject(SAVE_AS)
  private $terminals = inject(TERMINAL_FACTORY)
  private $activeModal = inject(NgbActiveModal)
  private $api = inject(ApiService)
  private $router = inject(Router)
  private $settings = inject(SettingsService)
  private $toastr = inject(ToastrService)
  private $translate = inject(TranslateService)
  private $ws = inject(WsService)
  private modalData = inject(SWITCH_TO_SCOPED_MODAL_DATA)

  // Public properties for component use
  public plugin = this.modalData.plugin

  // Signals
  public readonly installing = signal(false)
  public readonly installed = signal(false)
  public readonly uninstalling = signal(false)
  public readonly uninstalled = signal(false)
  public readonly restarting = signal(false)
  public readonly failure = signal<string>('')
  public readonly onlineUpdateOk = signal(false)

  // Other properties
  private io!: IoNamespace
  private term: Terminal
  private termTarget!: HTMLElement
  private fitAddon = this.$terminals.createFitAddon()
  private webLinksAddon = this.$terminals.createWebLinksAddon()
  private errorLog = ''
  private xtermA11yDisposer: (() => void) | null = null
  private stdoutHandler?: (data: string | Uint8Array) => void

  public readonly moreInfo = '<a href="https://github.com/homebridge/plugins/wiki/Scoped-Plugins" target="_blank"><i class="fas fa-up-right-from-square primary-text"></i></a>'
  public readonly prefix = '<span class="font-monospace">@homebridge-plugins/</span>'

  public get isLightTerminalTheme(): boolean {
    return this.$settings.getEffectiveTerminalLightingMode() === 'light'
  }

  constructor() {
    this.term = this.$terminals.createTerminal(this.$settings.getTerminalOptions({ disableStdin: true }))
    this.term.loadAddon(this.fitAddon)
    this.term.loadAddon(this.webLinksAddon)
  }

  public ngOnInit(): void {
    this.onlineUpdateOk.set(this.$settings.env.platform !== 'win32')
    this.io = this.$ws.connectToNamespace('plugins')
    this.termTarget = document.getElementById('plugin-output')!
    this.term.open(this.termTarget)
    this.xtermA11yDisposer = hideXtermInputFromScreenReader(this.termTarget)
    // Defer fit() to the next tick. The modal's host element can have
    // zero size on the first tick after open, so calling fit() inline
    // would size the terminal to 0×0 and the user sees a blank pane
    // until the next resize event.
    setTimeout(() => this.fitAddon.fit(), 0)

    this.stdoutHandler = (data: string | Uint8Array) => {
      this.term.write(data)
      const dataCleaned = data
        .toString()
        .replace(RE_ANSI, '')
        .trimEnd()
      if (dataCleaned) {
        this.errorLog += `${dataCleaned}\r\n`
      }
    }
    this.io.socket.on('stdout', this.stdoutHandler)
  }

  public async doSwitch(): Promise<void> {
    if (!this.plugin) {
      return
    }

    try {
      this.installing.set(true)

      // 1. Install new plugin
      await firstValueFrom(
        this.io.request('install', {
          name: this.plugin.newHbScope.to,
          version: this.plugin.newHbScope.switch,
          termCols: this.term.cols,
          termRows: this.term.rows,
        }),
      )

      this.installing.set(false)
      this.installed.set(true)
      this.uninstalling.set(true)

      // 2. Uninstall old plugin
      await firstValueFrom(
        this.io.request('uninstall', {
          name: this.plugin.newHbScope.from,
          termCols: this.term.cols,
          termRows: this.term.rows,
        }),
      )

      this.uninstalling.set(false)
      this.uninstalled.set(true)
      this.restarting.set(true)

      // 3. Set full service restart flag
      await this.$api.put('/platform-tools/hb-service/set-full-service-restart-flag', {})

      this.$activeModal.close()
      void this.$router.navigate(['/restart'])
    } catch (error) {
      if (this.installing()) {
        this.installing.set(false)
      }
      if (this.uninstalling()) {
        this.uninstalling.set(false)
      }
      if (this.restarting()) {
        this.restarting.set(false)
      }

      const message = error instanceof Error ? error.message : 'An error occurred'
      this.failure.set(message)
      console.error(error)
      this.$toastr.error(message, this.$translate.instant('toast.title_error'))
    }
  }

  public downloadLogFile(): void {
    if (!this.plugin) {
      return
    }

    const blob = new Blob([this.errorLog], { type: 'text/plain;charset=utf-8' })
    this.$saveAs(blob, `${this.plugin.name}-error.log`)
  }

  public ngOnDestroy(): void {
    // The plugins namespace is cached and shared, and `end()` keeps its
    // listeners, so detach ours before ending the session
    if (this.io && this.stdoutHandler) {
      this.io.socket.off('stdout', this.stdoutHandler)
    }
    this.io.end?.()
    this.xtermA11yDisposer?.()
    this.term.dispose()
  }

  public dismissModal(): void {
    this.$activeModal.dismiss('Dismiss')
  }
}
