// ui/src/modules/login/Login.tsx
import type { FormEvent } from 'react'

import { useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router'

import { authActions, useAuthStore } from '@/core/auth'
import { useSettingsStore } from '@/core/settings'
import { SafeHtml } from '@/core/ui/SafeHtml'
import { environment } from '@/environments/environment'

import './login.scss'

/** The pages a non-admin may be sent back to after signing in. */
const validNonAdminRoutes = [
  '/accessories',
  '/plugins',
  '/logs',
  '/support',
]

export interface LoginProps {
  /** Where to go once signed in (read from session storage by the route loader). */
  targetRoute?: string
}

/** The sign-in page (LoginComponent), with the 2FA code step. */
export function Login({ targetRoute = '/' }: LoginProps) {
  const { t } = useTranslation()
  const navigate = useNavigate()

  const usernameRef = useRef<HTMLInputElement>(null)
  const passwordRef = useRef<HTMLInputElement>(null)
  const otpRef = useRef<HTMLInputElement>(null)

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [otp, setOtp] = useState('')
  const [usernameDirty, setUsernameDirty] = useState(false)
  const [passwordDirty, setPasswordDirty] = useState(false)
  // Set on a second 412: the password is fine, the code is not. Cleared as
  // soon as the code changes (Angular's updateValueAndValidity)
  const [otpInvalidCode, setOtpInvalidCode] = useState(false)

  const [invalidCredentials, setInvalidCredentials] = useState(false)
  const [invalid2faCode, setInvalid2faCode] = useState(false)
  const [twoFactorCodeRequired, setTwoFactorCodeRequired] = useState(false)

  // The OTP field is optional until it appears, so its rules only apply then
  const otpInvalid = twoFactorCodeRequired && (otp.length !== 6 || otpInvalidCode)
  const formInvalid = !username || !password || otpInvalid

  const wallpaperHash = useSettingsStore(s => (s.settingsLoaded ? s.env.customWallpaperHash : undefined))
  const backgroundStyle = wallpaperHash
    ? `url('${environment.api.base}/auth/wallpaper/${wallpaperHash}') center/cover`
    : ''

  // Password managers write straight to the DOM without an input event, so the
  // native value is read back shortly after any change
  useEffect(() => {
    const timer = setTimeout(() => {
      const passwordInputValue = passwordRef.current?.value
      if (passwordInputValue && passwordInputValue !== password) {
        setPassword(passwordInputValue)
      }
    }, 500)
    return () => clearTimeout(timer)
  }, [username, password, otp])

  useEffect(() => {
    // Skip programmatic focus on touch devices: iOS Safari (and Android Chrome)
    // won't open the keyboard without a user gesture, so focusing here would
    // just show a focus ring without a keyboard — confusing UX.
    const isTouchDevice = window.matchMedia('(hover: none) and (pointer: coarse)').matches
    if (!isTouchDevice) {
      usernameRef.current?.focus()
    }
  }, [])

  // Cleared on unmount: a login that completes (and navigates away) within
  // 100ms would otherwise focus a field that no longer exists
  const focusTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined)
  useEffect(() => () => clearTimeout(focusTimerRef.current), [])

  const onSubmit = async (event?: FormEvent) => {
    event?.preventDefault()
    setInvalidCredentials(false)
    setInvalid2faCode(false)
    document.getElementById('submit-button')?.blur()

    // Grab the values from the native element as they may be "populated" via autofill.
    let form = { username, password, otp }
    const passwordInputValue = passwordRef.current?.value
    if (passwordInputValue && passwordInputValue !== form.password) {
      form = { ...form, password: passwordInputValue }
      setPassword(passwordInputValue)
    }

    const usernameInputValue = usernameRef.current?.value
    if (usernameInputValue && usernameInputValue !== form.username) {
      form = { ...form, username: usernameInputValue }
      setUsername(usernameInputValue)
    }

    if (twoFactorCodeRequired) {
      const otpInputValue = otpRef.current?.value
      if (otpInputValue && otpInputValue !== form.otp) {
        form = { ...form, otp: otpInputValue }
        setOtp(otpInputValue)
      }
    }

    try {
      await authActions.login(form)

      let target = targetRoute
      if (!useAuthStore.getState().user?.admin && !validNonAdminRoutes.includes(target)) {
        target = '/'
      }
      void navigate(target)
    } catch (error: any) {
      if (error?.status === 412) {
        if (twoFactorCodeRequired) {
          // 2FA already enabled but code was invalid
          setOtpInvalidCode(true)
          setInvalid2faCode(true)
        }

        setTwoFactorCodeRequired(true)
        clearTimeout(focusTimerRef.current)
        focusTimerRef.current = setTimeout(() => {
          document.getElementById('form-ota')?.focus()
        }, 100)
      } else {
        setInvalidCredentials(true)
      }
    }
  }

  const errorBox = (headline: string) => (
    <div className="input-group no-border mb-4">
      <div className="input-group-text custom-input">
        <i className="fas fa-exclamation-triangle pink-text fa-lg" aria-hidden="true"></i>
      </div>
      <div className="form-control custom-input">
        <div className="small grey-text fw-semibold">{headline}</div>
        <SafeHtml className="small grey-text" html={t('login.invalid_credentials_2')} />
      </div>
    </div>
  )

  return (
    <div
      className={`login-container gradient d-flex align-items-start justify-content-center${backgroundStyle ? '' : ' anim'}`}
      style={backgroundStyle ? { background: backgroundStyle } : undefined}
    >
      <div className="w-100 login-card d-flex py-4 flex-column">
        <img
          className="homebridge-logo mx-auto my-3"
          src="assets/homebridge-color-round.webp"
          alt="Homebridge Logo"
          height="100"
          width="100"
          fetchPriority="high"
        />
        <form noValidate onSubmit={event => void onSubmit(event)}>
          <h4 className="mb-4 text-center">{t('setup.welcome_to_homebridge')}</h4>
          {!twoFactorCodeRequired
            ? (
                <>
                  <div className="input-group mb-4">
                    <span className="input-group-text custom-input"><i className="fas fa-user primary-text fa-lg" aria-hidden="true"></i></span>
                    <input
                      ref={usernameRef}
                      name="username"
                      type="text"
                      id="form-username"
                      autoComplete="username"
                      autoCapitalize="none"
                      tabIndex={0}
                      className={`form-control custom-input${usernameDirty && !username ? ' is-invalid' : ''}`}
                      required
                      placeholder={t('users.label_username')}
                      value={username}
                      onChange={(e) => {
                        setUsername(e.target.value)
                        setUsernameDirty(true)
                      }}
                    />
                  </div>
                  <div className="input-group mb-4">
                    <span className="input-group-text custom-input"><i className="fas fa-lock primary-text fa-lg" aria-hidden="true"></i></span>
                    <input
                      ref={passwordRef}
                      name="password"
                      type="password"
                      id="form-pass"
                      autoComplete="current-password"
                      tabIndex={0}
                      className={`form-control custom-input${passwordDirty && !password ? ' is-invalid' : ''}`}
                      required
                      placeholder={t('users.label_password')}
                      value={password}
                      onChange={(e) => {
                        setPassword(e.target.value)
                        setPasswordDirty(true)
                      }}
                    />
                  </div>
                </>
              )
            : (
                <div className="input-group mb-4">
                  <span className="input-group-text custom-input"><i className="fas fa-key primary-text fa-lg" aria-hidden="true"></i></span>
                  <input
                    ref={otpRef}
                    type="text"
                    id="form-ota"
                    autoComplete="one-time-code"
                    autoCapitalize="none"
                    inputMode="numeric"
                    pattern="[0-9]*"
                    tabIndex={0}
                    className="form-control custom-input"
                    placeholder={t('login.label_2fa_code')}
                    value={otp}
                    onChange={(e) => {
                      setOtp(e.target.value)
                      setOtpInvalidCode(false)
                    }}
                  />
                </div>
              )}
          {invalidCredentials && errorBox(t('login.invalid_credentials'))}
          {invalid2faCode && errorBox(t('login.invalid_code'))}
          <div className="text-center">
            <button tabIndex={0} id="submit-button" className="btn btn-primary mb-2" type="submit" disabled={formInvalid}>
              {t('form.button_continue')}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// ui/src/app/modules/login/login.component.ts
import { NgOptimizedImage } from '@angular/common'
import { AfterViewInit, ChangeDetectionStrategy, Component, DestroyRef, ElementRef, inject, OnInit, signal, viewChild } from '@angular/core'
import { takeUntilDestroyed, toSignal } from '@angular/core/rxjs-interop'
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms'
import { Router } from '@angular/router'
import { TranslatePipe } from '@ngx-translate/core'
import { firstValueFrom } from 'rxjs'
import { debounceTime, map, startWith } from 'rxjs/operators'

import { AuthService } from '@/app/core/auth/auth.service'
import { SettingsService } from '@/app/core/ui/settings.service'
import { environment } from '@/environments/environment'

@Component({
  selector: 'app-login',
  imports: [
    FormsModule,
    ReactiveFormsModule,
    TranslatePipe,
    NgOptimizedImage,
  ],
  standalone: true,
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginComponent implements OnInit, AfterViewInit {
  private destroyRef = inject(DestroyRef)
  private $auth = inject(AuthService)
  private $router = inject(Router)
  private $settings = inject(SettingsService)
  private targetRoute!: string
  private validNonAdminRoutes = [
    '/accessories',
    '/plugins',
    '/logs',
    '/support',
  ]

  readonly passwordInput = viewChild<ElementRef>('password')
  readonly usernameInput = viewChild<ElementRef>('username')
  readonly otpInput = viewChild<ElementRef>('otp')

  public readonly backgroundStyle = signal<string>('')
  public readonly invalidCredentials = signal(false)
  public readonly invalid2faCode = signal(false)
  public readonly twoFactorCodeRequired = signal(false)
  public readonly inProgress = signal(false)

  // Initialize form as property with all controls (including OTP for 2FA)
  // OTP validators are added dynamically when 2FA is required
  public form = new FormGroup({
    username: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    password: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    otp: new FormControl('', { nonNullable: true }),
  })

  // Create signal for form validity state
  public readonly formInvalid = toSignal(
    this.form.statusChanges.pipe(
      startWith(this.form.status),
      map(() => this.form.invalid),
    ),
    { initialValue: this.form.invalid },
  )

  public ngOnInit() {
    this.form.valueChanges
      .pipe(
        debounceTime(500),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe(() => {
        const passwordInputValue = this.passwordInput()?.nativeElement.value
        if (passwordInputValue && passwordInputValue !== this.form.controls.password.value) {
          this.form.controls.password.setValue(passwordInputValue)
        }
      })

    // Read + remove atomically so a failed/abandoned login doesn't leave a
    // stale target_route in session storage for the next attempt
    this.targetRoute = window.sessionStorage.getItem('target_route') || '/'
    window.sessionStorage.removeItem('target_route')
    void this.setBackground()
  }

  public ngAfterViewInit() {
    // Skip programmatic focus on touch devices: iOS Safari (and Android Chrome)
    // won't open the keyboard without a user gesture, so focusing here would
    // just show a focus ring without a keyboard — confusing UX.
    const isTouchDevice = window.matchMedia('(hover: none) and (pointer: coarse)').matches
    if (!isTouchDevice) {
      this.usernameInput()?.nativeElement.focus()
    }
  }

  public async onSubmit() {
    this.invalidCredentials.set(false)
    this.invalid2faCode.set(false)
    this.inProgress.set(true)
    document.getElementById('submit-button')?.blur()

    // Grab the values from the native element as they may be "populated" via autofill.
    const passwordInputValue = this.passwordInput()?.nativeElement.value
    if (passwordInputValue && passwordInputValue !== this.form.controls.password.value) {
      this.form.controls.password.setValue(passwordInputValue)
    }

    const usernameInputValue = this.usernameInput()?.nativeElement.value
    if (usernameInputValue && usernameInputValue !== this.form.controls.username.value) {
      this.form.controls.username.setValue(usernameInputValue)
    }

    if (this.twoFactorCodeRequired()) {
      const otpInputValue = this.otpInput()?.nativeElement.value
      if (otpInputValue && otpInputValue !== this.form.controls.otp.value) {
        this.form.controls.otp.setValue(otpInputValue)
      }
    }

    try {
      await this.$auth.login(this.form.getRawValue())

      if (!this.$auth.user.admin && !this.validNonAdminRoutes.includes(this.targetRoute)) {
        this.targetRoute = '/'
      }
      void this.$router.navigateByUrl(this.targetRoute)
    } catch (error: any) {
      if (error.status === 412) {
        // Enable 2FA: add validators to the OTP control
        const otpControl = this.form.controls.otp

        if (!this.twoFactorCodeRequired()) {
          // First time enabling 2FA - set validators
          otpControl.setValidators([
            Validators.required,
            Validators.minLength(6),
            Validators.maxLength(6),
          ])
          otpControl.updateValueAndValidity()
        } else {
          // 2FA already enabled but code was invalid
          otpControl.setErrors({ invalidCode: true })
          this.invalid2faCode.set(true)
        }

        this.twoFactorCodeRequired.set(true)
        // Cleared on destroy: a login that completes (and navigates away)
        // within 100ms would otherwise focus a field that no longer exists
        const focusTimer = setTimeout(() => {
          document.getElementById('form-ota')?.focus()
        }, 100)
        this.destroyRef.onDestroy(() => clearTimeout(focusTimer))
      } else {
        this.invalidCredentials.set(true)
      }
    }
    this.inProgress.set(false)
  }

  private async setBackground() {
    if (!this.$settings.settingsLoaded) {
      await firstValueFrom(this.$settings.onSettingsLoaded)
    }

    if (this.$settings.env.customWallpaperHash) {
      const backgroundImageUrl = `${environment.api.base}/auth/wallpaper/${this.$settings.env.customWallpaperHash}`
      this.backgroundStyle.set(`url('${backgroundImageUrl}') center/cover`)
    }
  }
}
